package com.old.silence.job.server.domain.model;

import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;
import java.time.Instant;

/**
 * 锁定表
 *
 */
@TableName("sj_distributed_lock")
public class DistributedLock extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    /**
     * 锁名称
     */
    private String name;

    /**
     * 锁定时长
     */
    private Instant lockUntil;

    /**
     * 锁定时间
     */
    private Instant lockedAt;

    /**
     * 锁定者
     */
    private String lockedBy;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Instant getLockUntil() {
        return lockUntil;
    }

    public void setLockUntil(Instant lockUntil) {
        this.lockUntil = lockUntil;
    }

    public Instant getLockedAt() {
        return lockedAt;
    }

    public void setLockedAt(Instant lockedAt) {
        this.lockedAt = lockedAt;
    }

    public String getLockedBy() {
        return lockedBy;
    }

    public void setLockedBy(String lockedBy) {
        this.lockedBy = lockedBy;
    }
}
