package com.old.silence.job.server.domain.model;

import java.math.BigInteger;

import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditableTenantable;
import com.old.silence.job.common.enums.ExecutorType;

/**
 * @author moryzang
 */
@TableName("sj_job_executor")
public class JobExecutor extends AbstractAutoGeneratedIdAuditableTenantable<BigInteger, String> {


    /**
     * 组名称
     */
    private String groupName;

    /**
     * 定时任务执行器名称
     */
    private String executorInfo;

    /**
     * 1:java; 2:python; 3:go;
     */
    private ExecutorType executorType;


    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public String getExecutorInfo() {
        return executorInfo;
    }

    public void setExecutorInfo(String executorInfo) {
        this.executorInfo = executorInfo;
    }

    public ExecutorType getExecutorType() {
        return executorType;
    }

    public void setExecutorType(ExecutorType executorType) {
        this.executorType = executorType;
    }
}
