package com.old.silence.job.server.domain.model;

import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditableTenantable;
import com.old.silence.job.common.enums.NotifyType;

import java.math.BigInteger;

/**
 * 告警通知接收人
 *
 */
@TableName("sj_notify_recipient")
public class NotifyRecipient extends AbstractAutoGeneratedIdAuditableTenantable<BigInteger, String> {


    /**
     * 接收人名称
     */
    private String recipientName;

    /**
     * 通知类型 1、钉钉 2、邮件 3、企业微信 4 飞书
     */
    private NotifyType notifyType;

    /**
     * 配置属性
     */
    private String notifyAttribute;

    /**
     * 描述
     */
    private String description;


    public String getRecipientName() {
        return recipientName;
    }

    public void setRecipientName(String recipientName) {
        this.recipientName = recipientName;
    }

    public NotifyType getNotifyType() {
        return notifyType;
    }

    public void setNotifyType(NotifyType notifyType) {
        this.notifyType = notifyType;
    }

    public String getNotifyAttribute() {
        return notifyAttribute;
    }

    public void setNotifyAttribute(String notifyAttribute) {
        this.notifyAttribute = notifyAttribute;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
