package com.old.silence.job.server.domain.model;

import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditableTenantable;
import com.old.silence.job.common.enums.JobNotifyScene;
import com.old.silence.job.common.enums.SystemTaskType;

import java.math.BigInteger;

@TableName("sj_notify_config")
public class NotifyConfig extends AbstractAutoGeneratedIdAuditableTenantable<BigInteger, String> {



    private String groupName;

    /**
     * 通知告警场景名
     */
    private String notifyName;

    /**
     * 任务类型 1、重试任务 2、回调任务、 3、JOB任务 4、WORKFLOW任务
     */
    private SystemTaskType systemTaskType;

    private Boolean notifyStatus;

    private String recipientIds;

    private Integer notifyThreshold;

    private JobNotifyScene notifyScene;

    private Boolean rateLimiterStatus;

    private Integer rateLimiterThreshold;

    private String description;


    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public SystemTaskType getSystemTaskType() {
        return systemTaskType;
    }

    public void setSystemTaskType(SystemTaskType systemTaskType) {
        this.systemTaskType = systemTaskType;
    }

    public Boolean getNotifyStatus() {
        return notifyStatus;
    }

    public void setNotifyStatus(Boolean notifyStatus) {
        this.notifyStatus = notifyStatus;
    }

    public String getRecipientIds() {
        return recipientIds;
    }

    public void setRecipientIds(String recipientIds) {
        this.recipientIds = recipientIds;
    }

    public Integer getNotifyThreshold() {
        return notifyThreshold;
    }

    public void setNotifyThreshold(Integer notifyThreshold) {
        this.notifyThreshold = notifyThreshold;
    }

    public String getNotifyName() {
        return notifyName;
    }

    public void setNotifyName(String notifyName) {
        this.notifyName = notifyName;
    }

    public JobNotifyScene getNotifyScene() {
        return notifyScene;
    }

    public void setNotifyScene(JobNotifyScene notifyScene) {
        this.notifyScene = notifyScene;
    }

    public Boolean getRateLimiterStatus() {
        return rateLimiterStatus;
    }

    public void setRateLimiterStatus(Boolean rateLimiterStatus) {
        this.rateLimiterStatus = rateLimiterStatus;
    }

    public Integer getRateLimiterThreshold() {
        return rateLimiterThreshold;
    }

    public void setRateLimiterThreshold(Integer rateLimiterThreshold) {
        this.rateLimiterThreshold = rateLimiterThreshold;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
