package com.old.silence.job.server.domain.model;

import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditableTenantable;
import com.old.silence.job.common.enums.BackoffType;
import com.old.silence.job.common.enums.CbTriggerType;
import com.old.silence.job.common.enums.RetryBlockStrategy;
import com.old.silence.job.common.enums.TriggerType;

import java.math.BigInteger;

/**
 * 场景配置
 *
 */
@TableName("sj_retry_scene_config")
public class RetrySceneConfig extends AbstractAutoGeneratedIdAuditableTenantable<BigInteger, String> {


    private String groupName;

    private String sceneName;

    private RetryBlockStrategy blockStrategy;

    private Boolean sceneStatus;

    private Integer maxRetryCount;

    private BackoffType backOff;

    private String triggerInterval;

    private String description;

    private Long deadlineRequest;

    private Integer routeKey;

    private Integer executorTimeout;

    /**
     * 通知告警场景配置id列表
     */
    private String notifyIds;

    /**
     * 回调状态 0、不开启 1、开启
     */
    private Boolean cbStatus;

    /**
     * 回调触发类型
     */
    private CbTriggerType cbTriggerType;

    /**
     * 回调的最大执行次数
     */
    private int cbMaxCount;

    /**
     * 回调间隔时间
     */
    private String cbTriggerInterval;

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public String getSceneName() {
        return sceneName;
    }

    public void setSceneName(String sceneName) {
        this.sceneName = sceneName;
    }

    public RetryBlockStrategy getBlockStrategy() {
        return blockStrategy;
    }

    public void setBlockStrategy(RetryBlockStrategy blockStrategy) {
        this.blockStrategy = blockStrategy;
    }

    public Boolean getSceneStatus() {
        return sceneStatus;
    }

    public void setSceneStatus(Boolean sceneStatus) {
        this.sceneStatus = sceneStatus;
    }

    public Integer getMaxRetryCount() {
        return maxRetryCount;
    }

    public void setMaxRetryCount(Integer maxRetryCount) {
        this.maxRetryCount = maxRetryCount;
    }

    public BackoffType getBackOff() {
        return backOff;
    }

    public void setBackOff(BackoffType backOff) {
        this.backOff = backOff;
    }

    public String getTriggerInterval() {
        return triggerInterval;
    }

    public void setTriggerInterval(String triggerInterval) {
        this.triggerInterval = triggerInterval;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getDeadlineRequest() {
        return deadlineRequest;
    }

    public void setDeadlineRequest(Long deadlineRequest) {
        this.deadlineRequest = deadlineRequest;
    }

    public Integer getRouteKey() {
        return routeKey;
    }

    public void setRouteKey(Integer routeKey) {
        this.routeKey = routeKey;
    }

    public Integer getExecutorTimeout() {
        return executorTimeout;
    }

    public void setExecutorTimeout(Integer executorTimeout) {
        this.executorTimeout = executorTimeout;
    }

    public String getNotifyIds() {
        return notifyIds;
    }

    public void setNotifyIds(String notifyIds) {
        this.notifyIds = notifyIds;
    }

    public Boolean getCbStatus() {
        return cbStatus;
    }

    public void setCbStatus(Boolean cbStatus) {
        this.cbStatus = cbStatus;
    }

    public CbTriggerType getCbTriggerType() {
        return cbTriggerType;
    }

    public void setCbTriggerType(CbTriggerType cbTriggerType) {
        this.cbTriggerType = cbTriggerType;
    }

    public int getCbMaxCount() {
        return cbMaxCount;
    }

    public void setCbMaxCount(int cbMaxCount) {
        this.cbMaxCount = cbMaxCount;
    }

    public String getCbTriggerInterval() {
        return cbTriggerInterval;
    }

    public void setCbTriggerInterval(String cbTriggerInterval) {
        this.cbTriggerInterval = cbTriggerInterval;
    }
}
