package com.old.silence.job.server.domain.model;

import com.baomidou.mybatisplus.annotation.FieldStrategy;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditableTenantable;
import com.old.silence.job.common.enums.IdGeneratorMode;

import java.math.BigInteger;

/**
 * 组配置
 *
 */
@TableName("sj_group_config")
public class GroupConfig extends AbstractAutoGeneratedIdAuditableTenantable<BigInteger, String> {


    @TableField(updateStrategy = FieldStrategy.NEVER)
    private String groupName;

    private Boolean groupStatus;

    private Integer groupPartition;

    private IdGeneratorMode idGeneratorMode;

    @TableField(value = "version", update = "%s+1")
    private Integer version;

    private Boolean initScene;

    @TableField(updateStrategy = FieldStrategy.NEVER)
    private String token;

    private String description;


    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public Boolean getGroupStatus() {
        return groupStatus;
    }

    public void setGroupStatus(Boolean groupStatus) {
        this.groupStatus = groupStatus;
    }

    public Integer getGroupPartition() {
        return groupPartition;
    }

    public void setGroupPartition(Integer groupPartition) {
        this.groupPartition = groupPartition;
    }

    public IdGeneratorMode getIdGeneratorMode() {
        return idGeneratorMode;
    }

    public void setIdGeneratorMode(IdGeneratorMode idGeneratorMode) {
        this.idGeneratorMode = idGeneratorMode;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Boolean getInitScene() {
        return initScene;
    }

    public void setInitScene(Boolean initScene) {
        this.initScene = initScene;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
