package com.old.silence.job.server.domain.model;

import com.baomidou.mybatisplus.annotation.TableLogic;
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableField;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditableTenantable;

import java.math.BigInteger;

/**
 * 任务-通知配置关联表
 * 用于维护任务与通知配置的多对多关系
 * 
 * @author Auto Generated
 * @since 2026-03-17
 */
@TableName("sj_job_notify_config_relation")
public class JobNotifyConfigRelation extends AbstractAutoGeneratedIdAuditableTenantable<BigInteger, String> {

    /**
     * 任务ID
     */
    private BigInteger jobId;

    /**
     * 通知配置ID
     */
    private BigInteger notifyConfigId;

    @TableLogic
    @TableField(value = "is_deleted")
    private Boolean deleted;

    // ==================== Constructors ====================

    public JobNotifyConfigRelation() {
    }

    public JobNotifyConfigRelation(BigInteger jobId, BigInteger notifyConfigId) {
        this.jobId = jobId;
        this.notifyConfigId = notifyConfigId;
    }

    // ==================== Getters & Setters ====================

    public BigInteger getJobId() {
        return jobId;
    }

    public void setJobId(BigInteger jobId) {
        this.jobId = jobId;
    }

    public BigInteger getNotifyConfigId() {
        return notifyConfigId;
    }

    public void setNotifyConfigId(BigInteger notifyConfigId) {
        this.notifyConfigId = notifyConfigId;
    }

    public Boolean getDeleted() {
        return deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    // ==================== toString ====================

    @Override
    public String toString() {
        return "JobNotifyConfigRelation{" +
                "id=" + id +
                ", jobId=" + jobId +
                ", notifyConfigId=" + notifyConfigId +
                ", tenantId='" + tenantId + '\'' +
                ", deleted=" + deleted +
                '}';
    }
}
