package com.old.silence.job.server.domain.model;

import com.baomidou.mybatisplus.annotation.TableLogic;
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableField;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditableTenantable;

import java.math.BigInteger;

/**
 * 通知配置-收件人关联表
 * 用于维护通知配置与收件人的多对多关系
 * 
 * @author Auto Generated
 * @since 2026-03-17
 */
@TableName("sj_notify_config_recipient_relation")
public class NotifyConfigRecipientRelation extends AbstractAutoGeneratedIdAuditableTenantable<BigInteger, String> {

    /**
     * 通知配置ID
     */
    private BigInteger notifyConfigId;

    /**
     * 收件人ID
     */
    private BigInteger recipientId;

    @TableLogic
    @TableField(value = "is_deleted")
    private Boolean deleted;

    // ==================== Constructors ====================

    public NotifyConfigRecipientRelation() {
    }

    public NotifyConfigRecipientRelation(BigInteger notifyConfigId, BigInteger recipientId) {
        this.notifyConfigId = notifyConfigId;
        this.recipientId = recipientId;
    }

    // ==================== Getters & Setters ====================

    public BigInteger getNotifyConfigId() {
        return notifyConfigId;
    }

    public void setNotifyConfigId(BigInteger notifyConfigId) {
        this.notifyConfigId = notifyConfigId;
    }

    public BigInteger getRecipientId() {
        return recipientId;
    }

    public void setRecipientId(BigInteger recipientId) {
        this.recipientId = recipientId;
    }

    public Boolean getDeleted() {
        return deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    // ==================== toString ====================

    @Override
    public String toString() {
        return "NotifyConfigRecipientRelation{" +
                "id=" + id +
                ", notifyConfigId=" + notifyConfigId +
                ", recipientId=" + recipientId +
                ", tenantId='" + tenantId + '\'' +
                ", deleted=" + deleted +
                '}';
    }
}
