package com.old.silence.job.server.domain.model;

import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;

/**
 * 通知配置-收件人关联表
 * 用于维护通知配置与收件人的多对多关系
 *
 * @author Auto Generated
 * @since 2026-03-17
 */
@TableName("sj_notify_config_recipient_relation")
public class NotifyConfigRecipientRelation extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    /**
     * 通知配置ID
     */
    private BigInteger notifyConfigId;

    /**
     * 收件人ID
     */
    private BigInteger recipientId;

    public NotifyConfigRecipientRelation() {
    }

    public NotifyConfigRecipientRelation(BigInteger notifyConfigId, BigInteger recipientId) {
        this.notifyConfigId = notifyConfigId;
        this.recipientId = recipientId;
    }

    public BigInteger getNotifyConfigId() {
        return notifyConfigId;
    }

    public void setNotifyConfigId(BigInteger notifyConfigId) {
        this.notifyConfigId = notifyConfigId;
    }

    public BigInteger getRecipientId() {
        return recipientId;
    }

    public void setRecipientId(BigInteger recipientId) {
        this.recipientId = recipientId;
    }

    @Override
    public String toString() {
        return "NotifyConfigRecipientRelation{" +
                "id=" + getId() +
                ", notifyConfigId=" + notifyConfigId +
                ", recipientId=" + recipientId +
                '}';
    }
}
