package com.old.silence.job.server.domain.model;

import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditableTenantable;

import java.math.BigInteger;

/**
 * 重试日志异常信息记录表
 *
 */
@TableName("sj_retry_task_log_message")
public class RetryTaskLogMessage extends AbstractAutoGeneratedIdAuditableTenantable<BigInteger, String> {



    /**
     * 组名称
     */
    private String groupName;

    /**
     * 重试任务id
     */
    private BigInteger retryTaskId;

    /**
     * 重试信息Id
     */
    private BigInteger retryId;

    /**
     * 异常信息
     */
    private String message;

    /**
     * 日志数量
     */
    private Integer logNum;

    /**
     * 真实上报时间
     */
    private Long realTime;

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public BigInteger getRetryTaskId() {
        return retryTaskId;
    }

    public void setRetryTaskId(BigInteger retryTaskId) {
        this.retryTaskId = retryTaskId;
    }

    public BigInteger getRetryId() {
        return retryId;
    }

    public void setRetryId(BigInteger retryId) {
        this.retryId = retryId;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Integer getLogNum() {
        return logNum;
    }

    public void setLogNum(Integer logNum) {
        this.logNum = logNum;
    }

    public Long getRealTime() {
        return realTime;
    }

    public void setRealTime(Long realTime) {
        this.realTime = realTime;
    }
}
