package com.old.silence.job.server.domain.model;

import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;

/**
 * 重试场景配置-通知配置关联表
 * 用于维护重试场景配置与通知配置的多对多关系
 * 
 * @author Auto Generated
 * @since 2026-03-17
 */
@TableName("sj_retry_scene_config_notify_config_relation")
public class RetrySceneConfigNotifyConfigRelation extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    /**
     * 重试场景配置ID
     */
    private BigInteger retrySceneConfigId;

    /**
     * 通知配置ID
     */
    private BigInteger notifyConfigId;

    // ==================== Constructors ====================

    public RetrySceneConfigNotifyConfigRelation() {
    }

    public RetrySceneConfigNotifyConfigRelation(BigInteger retrySceneConfigId, BigInteger notifyConfigId) {
        this.retrySceneConfigId = retrySceneConfigId;
        this.notifyConfigId = notifyConfigId;
    }

    // ==================== Getters & Setters ====================

    public BigInteger getRetrySceneConfigId() {
        return retrySceneConfigId;
    }

    public void setRetrySceneConfigId(BigInteger retrySceneConfigId) {
        this.retrySceneConfigId = retrySceneConfigId;
    }

    public BigInteger getNotifyConfigId() {
        return notifyConfigId;
    }

    public void setNotifyConfigId(BigInteger notifyConfigId) {
        this.notifyConfigId = notifyConfigId;
    }

    // ==================== toString ====================

    @Override
    public String toString() {
        return "RetrySceneConfigNotifyConfigRelation{" +
                "id=" + getId() +
                ", retrySceneConfigId=" + retrySceneConfigId +
                ", notifyConfigId=" + notifyConfigId +
                '}';
    }
}
