package com.old.silence.job.server.domain.model;

import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;

/**
 * 重试场景配置-通知配置关联表
 * 用于维护重试场景配置与通知配置的多对多关系
 * 
 * @author Auto Generated
 * @since 2026-03-17
 */
@TableName("sj_retry_scene_config_notify_config_relation")
public class RetrySceneConfigNotifyConfigRelation extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    /**
     * 重试场景配置ID
     */
    private BigInteger retrySceneConfigId;

    /**
     * 通知配置ID
     */
    private BigInteger notifyConfigId;

    @ManyToOne
    @JoinColumn(name = "retry_scene_config_id", referencedColumnName = "id")
    private RetrySceneConfig retrySceneConfig;

    public BigInteger getRetrySceneConfigId() {
        return retrySceneConfigId;
    }

    public void setRetrySceneConfigId(BigInteger retrySceneConfigId) {
        this.retrySceneConfigId = retrySceneConfigId;
    }

    public BigInteger getNotifyConfigId() {
        return notifyConfigId;
    }

    public void setNotifyConfigId(BigInteger notifyConfigId) {
        this.notifyConfigId = notifyConfigId;
    }

    public RetrySceneConfig getRetrySceneConfig() {
        return retrySceneConfig;
    }

    public void setRetrySceneConfig(RetrySceneConfig retrySceneConfig) {
        this.retrySceneConfig = retrySceneConfig;
    }
}
