package com.old.silence.job.server.domain.model;

import com.baomidou.mybatisplus.annotation.TableLogic;
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableField;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditableTenantable;

import java.math.BigInteger;

/**
 * 工作流-通知配置关联表
 * 用于维护工作流与通知配置的多对多关系
 * 
 * @author Auto Generated
 * @since 2026-03-17
 */
@TableName("sj_workflow_notify_config_relation")
public class WorkflowNotifyConfigRelation extends AbstractAutoGeneratedIdAuditableTenantable<BigInteger, String> {

    /**
     * 工作流ID
     */
    private BigInteger workflowId;

    /**
     * 通知配置ID
     */
    private BigInteger notifyConfigId;

    @TableLogic
    @TableField(value = "is_deleted")
    private Boolean deleted;

    // ==================== Constructors ====================

    public WorkflowNotifyConfigRelation() {
    }

    public WorkflowNotifyConfigRelation(BigInteger workflowId, BigInteger notifyConfigId) {
        this.workflowId = workflowId;
        this.notifyConfigId = notifyConfigId;
    }

    // ==================== Getters & Setters ====================

    public BigInteger getWorkflowId() {
        return workflowId;
    }

    public void setWorkflowId(BigInteger workflowId) {
        this.workflowId = workflowId;
    }

    public BigInteger getNotifyConfigId() {
        return notifyConfigId;
    }

    public void setNotifyConfigId(BigInteger notifyConfigId) {
        this.notifyConfigId = notifyConfigId;
    }

    public Boolean getDeleted() {
        return deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    // ==================== toString ====================

    @Override
    public String toString() {
        return "WorkflowNotifyConfigRelation{" +
                "id=" + id +
                ", workflowId=" + workflowId +
                ", notifyConfigId=" + notifyConfigId +
                ", tenantId='" + tenantId + '\'' +
                ", deleted=" + deleted +
                '}';
    }
}
