package com.old.silence.job.server.domain.model;

import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;

/**
 * 工作流-通知配置关联表
 * 用于维护工作流与通知配置的多对多关系
 * 
 * @author Auto Generated
 * @since 2026-03-17
 */
@TableName("sj_workflow_notify_config_relation")
public class WorkflowNotifyConfigRelation extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    /**
     * 工作流ID
     */
    private BigInteger workflowId;

    /**
     * 通知配置ID
     */
    private BigInteger notifyConfigId;

    // ==================== Constructors ====================

    public WorkflowNotifyConfigRelation() {
    }

    public WorkflowNotifyConfigRelation(BigInteger workflowId, BigInteger notifyConfigId) {
        this.workflowId = workflowId;
        this.notifyConfigId = notifyConfigId;
    }

    // ==================== Getters & Setters ====================

    public BigInteger getWorkflowId() {
        return workflowId;
    }

    public void setWorkflowId(BigInteger workflowId) {
        this.workflowId = workflowId;
    }

    public BigInteger getNotifyConfigId() {
        return notifyConfigId;
    }

    public void setNotifyConfigId(BigInteger notifyConfigId) {
        this.notifyConfigId = notifyConfigId;
    }

    // ==================== toString ====================

    @Override
    public String toString() {
        return "WorkflowNotifyConfigRelation{" +
                "id=" + getId() +
                ", workflowId=" + workflowId +
                ", notifyConfigId=" + notifyConfigId +
                '}';
    }
}
